import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Layout>
    <h1>
      Hello world!
    </h1>
    accusamus magnam nam tempore ullam. Nisi cum fugit nulla illum accusamus obcaecati rerum minus ipsam tenetur amet tempora consequatur, perferendis exercitationem adipisci repudiandae. Atque optio officiis pariatur commodi fuga fugiat ab reiciendis rerum alias quia necessitatibus, ut deserunt quo reprehenderit vero nemo odio libero excepturi ipsam, sint temporibus molestiae minus corporis!
    </Layout>
    </>
  );
};

export default Home;
